[engine]
version = "0.0.0"


[world]
entry_scene = "world.scene"
gravity.x = 0.0
gravity.y = -9.8


[window]
title = "test game"
width = 800
height = 600 
msaa_sample_count = 4
high_dpi = false
fullscreen = false
allow_transparency = true 
